// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shopapp.Data;

namespace shopapp.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20191204155946_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("shopapp.Model.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("product_description")
                        .HasColumnType("TEXT");

                    b.Property<string>("product_image")
                        .HasColumnType("TEXT");

                    b.Property<string>("product_name")
                        .HasColumnType("TEXT");

                    b.Property<float>("product_price")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("product");
                });
#pragma warning restore 612, 618
        }
    }
}
